CREATE DATABASE EMPLOYEE_MANAGEMENT;
USE EMPLOYEE_MANAGEMENT;

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20),
AGE INT,
DEPARTMENT VARCHAR(30),
DESIGNATION VARCHAR(30),
SALARY DECIMAL(10,2) ,
PHONE_NO VARCHAR(15),
EMAIL_ID VARCHAR(50) UNIQUE,
JOINING_DATE  DATE,
REMARK VARCHAR(100)
 );

 